### ISSUE TITLE
404 links in tutorials

### ISSUE THREAD

**Issue by onlinelaser** [AdobeDocs/cc-libraries-api#22]
### Expected Behaviour
Closing links on this page https://www.adobe.io/creative-cloud-libraries/docs/integrate/tutorials/quick-start-nodejs/ should lead to subsequent pages in the tutorial!

### Actual Behaviour
404's on:
https://www.adobe.io/creative-cloud-libraries/docs/integrate/tutorials/quick-start-nodejs/getting-data/nodejs.md
https://www.adobe.io/creative-cloud-libraries/docs/integrate/tutorials/quick-start-nodejs/quick-start-curl.md

**Comment by ashryanbeats** [comment]
Thanks for reporting this!
